<?php

namespace Database\Seeders;

use App\Models\StudyProgram;
use Illuminate\Database\Seeder;

class StudyProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $programs = [
            1 => [
                'Program Pendidikan Sarjana Farmasi Reguler',
                'Program Pendidikan Sarjana Farmasi Paralel',
                'Program Pendidikan Profesi Apoteker',
                'Program Pendidikan Magister Ilmu Herbal kekhususan Herbal Medis',
                'Program Pendidikan Magister Ilmu Herbal kekhususan Herbal Estetika',
                'Program Pendidikan Magister Farmasi Kekhususan Biologi Farmasi',
                'Program Pendidikan Magister Farmasi Kekhususan Farmasi Klinik',
                'Program Pendidikan Magister Farmasi Kekhususan Kimia Farmasi',
                'Program Pendidikan Magister Farmasi Kekhususan Teknologi Farmasi',
                'Program Pendidikan Magister Farmasi Kekhususan Bioteknologi Farmasi',
                'Program Pendidikan Magister Farmasi Kekhususan Farmakologi dan Toksikologi',
                'Doktor Ilmu Farmasi',
            ],
            2 => [
                'Subprogram Sarjana Reguler',
                'Subprogram Sarjana Paralel',
                'Subprogram Sarjana Ekstensi',
                'Subprogram Magister Ilmu Hukum',
                'Subprogram Magister Kenotariatan',
                'Program Doktor Ilmu Hukum',
                'Internasional',
            ],
            3 => [
                'Ilmu Administrasi Niaga',
                'Ilmu Administrasi Fiskal',
                'Ilmu Administrasi Negara',
                'Administrasi dan Kebijakan Publik',
                'Administrasi dan Kebijakan Perpajakan',
                'Studi Pemerintahan Daerah',
                'E-Government',
                'Administrasi dan Kebijakan Niaga',
                'Analisis Kebijakan Publik',
                'Inovasi dan Intrapreneurial',
                'Administrasi dan Kebijakan PSDM Sektor Publik',
                'Administrasi Pajak Daerah dan Retribusi Daerah',
                'Administrasi Keuangan dan Aset Daerah',
                'Administrasi Pengawasan',
                'Administrasi dan Kebijakan Publik',
                'Kelas Khusus E-Gov',
                'Program Doktor Ilmu Administrasi',
                'Program Pra Universitas',
            ],
            4 => [
                'Bahasa dan Kebudayaan Korea',
                'Sastra Belanda',
                'Arkeologi',
                'Program Studi Filsafat',
                'Program Studi Ilmu Perpustakaan',
                'Program Studi Ilmu Sejarah',
                'Sastra Arab',
                'Sastra Cina',
                'Sastra Indonesia',
                'Sastra Inggris',
                'Sastra Jepang',
                'Sastra Jerman',
                'Sastra Perancis',
                'Sastra Slavia',
                'Arkeologi',
                'Ilmu Filsafat',
                'Ilmu Sejarah',
                'Ilmu Perpustakaan',
                'Ilmu Sejarah',
                'Linguistik',
                'Asia Tenggara',
                'Arkeologi',
                'Ilmu Filsafat',
                'Ilmu Sejarah',
                'Ilmu Susastra',
                'Ilmu Susastra',
                'Ilmu Linguistik',
            ],
            5 => [
                'Manajemen',
                'Akuntansi',
                'Ilmu Ekonomi',
                'Bisnis Islam',
                'Ilmu Ekonomi Islam'
            ],
            6 => [
                'Program Studi Ilmu Keperawatan',
                'Program Studi Profesi Ners',
                'Program Spesialis Keperawatan Komunitas',
                'Program Spesialis Ilmu Keperawatan Maternitas',
                'Program Spesialis  Keperawatan Anak',
                'Program Spesialis Keperawatan Jiwa',
                'Ilmu Keperawatan',
            ],
            7 => [
                'Sarjana Ilmu Komputer (Reguler)',
                'Sarjana Sistem Informasi',
                'Sarjana Ilmu Komputer (Kelas Khusus Internasional)',
                'Magister Ilmu Komputer',
                'Magister Teknologi Informasi (E-government)',
                'Magister Teknologi Informasi',
                'Doktor Ilmu Komputer',
            ],
            8 => [
                'Ilmu Komunikasi',
                'Ilmu Politik',
                'Kriminologi',
                'Sosiologi',
                'Ilmu Kesejahteraan Sosial',
                'Antropologi Sosial',
                'Ilmu Hubungan Internasional',
                'Program Sarjana Komunikasi (KKI)',
                'Magister Ilmu Komunikasi',
                'Magister Ilmu Politik',
                'Magister Kriminologi',
                'Magister Sosiologi',
                'Magister Ilmu Kesejahteraan Sosial',
                'Magister Antropologi',
                'Magister Ilmu Hubungan Internasional',
                'Doktor Ilmu Komunikasi',
                'Doktor Ilmu Politik',
                'Doktor Kriminologi',
                'Doktor Sosiologi',
                'Doktor Ilmu Kesejahteraan Sosial',
                'Doktor Antropologi',
            ],
            9 => [
                'Sarjana Kedokteran',
                'Ilmu Biomedik',
                'Ilmu Gizi',
                'Ilmu Kedokteran',
                'Kedokteran Kerja',
                'Anestesiologi dan Terapi Intensif',
                'Farmakologi Klinik ',
                'Ilmu Bedah',
                'Program Spesialis Ilmu Bedah Plastik',
                'Program Spesialis Ilmu Bedah Syaraf',
                'Program Spesialis Ilmu Kedokteran Forensik',
                'Program Pendidikan Spesialis Ilmu Kesehatan Jiwa',
                'Program Pendidikan Spesialis Ilmu Kesehatan Anak',
                'Program Spesialis Ilmu Kesehatan Kulit dan Kelamin',
                'Program Spesialis Ilmu Kesehatan Mata',
                'Program Spesialis Ilmu Orthopaedi dan Traumatologi',
                'Program Spesialis Ilmu Penyakit Dalam',
                'Program Spesialis Ilmu Penyakit Jantung dan Pembuluh Darah',
                'Program Spesialis Ilmu Penyakit Saraf',
                'Program Spesialis Ilmu Penyakit Telinga, Hidung dan Tenggorokan',
                'Program Spesialis Kedokteran Okupasi',
                'Program Spesialis Kedokteran Olahraga',
                'Program Spesialis Kedokteran Penerbangan',
                'Program Spesialis Mikrobiologi Klinik',
                'Progam Spesialis Obstetri Dan Ginekologi',
                'Program Spesialis Patologi Klinik',
                'Program Spesialis Pulmonologi dan Respirasi',
                'Program Spesialis Urologi',
                'Program Spesialis Ilmu Rehabilitasi Medik',
                'Program Spesialis 2 Ilmu Bedah',
                'Program Spesialis 2 Ilmu Kesehatan Anak',
                'Program Spesialis 2 Ilmu Penyakit Dalam',
                'Program Sarjana Kedokteran (Internasional)'
            ],
            10=>[
                'Program Pendidikan Kedokteran Gigi',
                'Magister Ilmu Kedokteran Gigi Dasar',
                'Magister Kedokteran Gigi Komunitas',
                'Doktor Kedokteran Gigi',
                'Program Spesialis Ilmu Bedah Mulut',
                'Program Spesialis llmu Kesehatan Gigi Anak',
                'Program Spesialis Ilmu Konservasi Gigi',
                'Program Spesialis Ilmu Penyakit Mulut',
                'Program Spesialis Ortodonsia',
                'Program Spesialis Periodonsia',
                'Program Spesialis Prostodonsia',

            ],
            11=>[
                'Kesehatan Lingkungan',
                'Kesehatan Masyarakat',
                'Studi Gizi',
                'Magister Administrasi Rumah Sakit',
                'Magister Epidemiologi',
                'Magister Ilmu Kesehatan Masyarakat',
                'Magister Kesehatan dan Keselamatan Kerja',
                'Ilmu Epidemiologi',
            ],
            12 => [
                'Program Studi Matematika',
                'Program Studi Fisika',
                'Program Studi Kimia',
                'Program Studi Biologi',
                'Program Studi Geografi',
                'Magister Matematika',
                'Magister Fisika',
                'Magister Biologi',
                'Magister Geografi',
                'Magister Ilmu Bahan-bahan',
                'Magister Ilmu Kelautan',
                'Magister Ilmu Kimia',
                'Magister Fisika Medis',
            ],
            13=>[
                'Psikologi (Reguler)',
                'Program Sarjana Psikologi ( Kelas Khusus Internasional)',
                'Magister Ilmu Psikologi',
                'Magister Psikologi Profesi',
                'Magister Psikologi Terapan',
                'Doktor Psikologi',
            ],
            14 => [
                'Teknik Sipil',
                'Teknik Lingkungan',
                'Teknik Mesin',
                'Teknik Perkapalan',
                'Teknik Elektro',
                'Teknik Komputer',
                'Teknik Industri',
                'Teknologi Bioproses',
                'Teknik Metalurgi ',
                'Teknik Arsitektur',
                'Arsitektur Interior',
                'Teknik Kimia',
                'Teknologi Bioproses',
                'Teknik Sipil (Internasional)',
                'Teknik Mesin (Internasional)',
                'Teknik Elektro (Internasional)',
                'Teknik Metalurgi & Material (Internasional)',
                'Arsitektur (Internasional)',
                'Teknik Kimia (Internasional)',
                'Magister Teknik Mesin',
                'Magister Teknik Kimia',
                'Magister Teknik Elektro',
                'Magister Teknik Metalurgi & Material',
                'Magister Arsitektur',
                'Magister Teknik Industri',
                'Magister Teknologi Biomedis',
                'Manajemen Integritas Material',
                'Perencanaan Wilayah dan Kota',
                'Teknik Lingkungan (S2)',
                'Teknik Sistem Energi',
                'Doktor Arsitektur'
            ],
            15=>[
                'Administrasi Rumah Sakit',
                'Administrasi Perpajakan',
                'Administrasi Asuransi dan Aktuaria',
                'Administrasi Keuangan dan Perbankan',
                'Administrasi Perkantoran',
                'Akuntansi',
                'Hubungan Masyarakat',
                'Penyiaran Multimedia',
                'Periklanan Kreatif',
                'Manajemen Informasi dan Dokumen',
                'Pendidikan Vokasional Pariwisata',
                'Produksi Media',
                'Bisnis Kreatif',
                'Fisioterapi',
                'Terapi Okupasi',
            ],
            16 => [
                'Magister Kajian Ilmu Lingkungan',
                'Magister Manajemen Bencana',
                'Program Doktor Ilmu Lingkungan'
            ],
            17 => [
                'Magister Kajian Gender',
                'Magister Kajian Ilmu Kepolisian',
                'Magister Kajian Kependudukan & Ketenagaan Kerja',
                'Magister Kajian Ketahanan Nasional',
                'Magister Kajian Pengembangan Perkotaan',
                'Magister Kajian Wilayah Amerika',
                'Magister Kajian Wilayah Eropa',
                'Magister Kajian Wilayah Jepang',
                'Magister Kajian Wilayah Timur Tengah Islam',
                'Kajian Stratejik Ketahanan Nasional (S3)',
                'Kajian kepolisian (S3)',
                'Kajian Terorisme (S3)',
                'Kajian Gender (S3)',
                'Kajian Pengembangan Perkotaan (S3)',
                'Kajian Wilayah Amerika (S3)',
                'Kajian Wilayah Eropa (S3)',
                'Kajian Wilayah Jepang dan Asia Timur (S3)',
                'Kajian Wilayah Timur Tengah (S3)',
                'Kajian Islam (S3)'
            ],
        ];

        foreach ($programs as $faculty_id => $programList) {
            foreach ($programList as $program) {
                StudyProgram::create([
                    'name' => $program,
                    'faculty_id' => $faculty_id,
                ]);
            }
        }
    }
}
